# Generated by Django 5.1 on 2024-11-15 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_people_instructor_id_remove_people_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_codes',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.people'),
        ),
    ]
