# Generated by Django 5.1 on 2024-11-13 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_people_person_type_alter_people_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='person_type',
        ),
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='instructor_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='people',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'is_instructor': True}, on_delete=django.db.models.deletion.CASCADE, to='app.people'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_instructor': False}, on_delete=django.db.models.deletion.CASCADE, to='app.people'),
        ),
    ]
